[package]
name = "automate-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
chrono = { version = "0.4.40", features = ["serde"] }
clap = { version = "4.5.53", features = ["cargo", "derive", "string"] }
cron = "0.15.0"
croner = { version = "3.0.1", features = ["serde"] }
feed-rs = "2.3.1"
fjall = "2.8.0"
htmd = "0.5.0"
html-escape = "0.2.13"
human-errors = "0.2.1"
icalendar = "0.16.13"
inventory = "0.3.21"
reqwest = { version = "0.12.15", features = ["blocking"] }
rstest = "0.25.0"
rusqlite = { version = "0.37.0", features = ["bundled", "chrono"] }
scraper = "0.24.0"
serde = { version = "1.0.219", features = ["alloc", "derive"] }
serde_json = { version = "1.0.140", features = ["alloc"] }
todoist-api = "0.3.0"
tokio = { version = "1.44.1", features = ["net", "io-std", "rt-multi-thread", "time", "fs"] }
tokio-rusqlite = "0.7.0"
toml = "0.9.8"
tracing-batteries = { git = "https://github.com/sierrasoftworks/tracing-batteries-rs.git", features = [
  "medama",
  "opentelemetry",
] }
urlencoding = "2.1.3"
uuid = "1.19.0"

[dev-dependencies]
wiremock = "0.6"
